### ISSUE TITLE
Написать оформленное ТЗ

### ISSUE THREAD

**Issue by KPbISSKA** [KPbISSKA/Tarasow_Aleksander#2]

**Comment by KPbISSKA** [comment]
1.Техническое задание

1.1. Общие сведения:

1.1.1. Полное наименование системы:
Приложение для изучения иностранных слов в учебных заведениях

1.1.2. Наименования организации-заказчика, разработчика системы:
Заказчик: КФ МГТУ им. Н. Э. Баумана
Разработчик: Студент КФ МГТУ им. Н. Э. Баумана группы ИУК5-51Б Тарасов А.П.

1.1.3. Плановые сроки начала и окончания работы по созданию системы:
Плановый срок начала работ – 12 сентября 2022 года.
Плановый срок окончания работ – 1 декабря 2022 года.

1.2. Назначение и цели создания системы

1.2.1. Назначение системы:
Система предназначена для преподавателей и студентов учебных учреждений, изучающих иностранные языки.

1.2.2. Цели создания системы:
Система создается для удобного изучения иностранных слов в учебном учреждении и автоматизации контроля знаний.

1.3. Требования к системе

1.3.1. Требования к системе в целом:

1.3.1.1. Требования к структуре и функционированию системы:
Система должна быть разделена на 2 подструктуры:

-Клиентская часть
-База данных

1.3.1.2. Требования по эргономике и технической эстетике:
Интерфейс системы не должен вводить пользователя в заблуждение, содержать элементы, назначение которых неочевидно или элементы, функционал которых отсутствует или не соответствует пояснению в интерфейсе. Интерфейс должен быть понятен и не перегружен графическими элементами.

1.3.2. Требования к функциям (задачам), выполняемым системой
Система должна реализовывать разные возможности в зависимости от типа пользователя.

Возможности администратора:
-Добавление и редактирование новых пользователей в системе
-Добавление и редактирование групп студентов

Возможности преподавателя:
-Добавление и редактирование достоверных слов в общем словаре системы
-Добавление и редактирование модулей для закрепления знания слов
-Доступ к статистике прохождения модулей студентами

Возможности студента:
-Доступ к чтению общего словаря системы и выбор слов для изучения
-Возможность добавления личных переводов слов
-Прохождение модулей, созданных преподавателем
-Прохождение личных проверок слов
-Просмотр личной статистики

1.3.3. Требования к видам обеспечения

1.3.3.1. Требования к лингвистическому обеспечению системы
Средством описания предметной области, также, как и средством взаимодействия пользователя с системой является русский язык.

1.3.3.2. Требования к входным и выходным данным

Входные данные должны быть организованы в виде вводимого в специальные формы текста, соответствующего определённому шаблону.
Выходные данные программы должны быть организованы в виде таблиц. Доступ к таблицам зависит от принадлежности пользователя к определённой группе(наличия роли).

1.3.3.3. Требования к программному обеспечению системы

В качестве языка программирования для разработки клиентской части в системе используется C#.
В качестве базы данных используется PostgreSQL.

1.4 Состав и содержание работ по созданию (развитию) системы

Утверждение темы, задания на разработку, технического задания (альфа). Оформление ТЗ. Описание предметной области и требований к системе. Концептуальная схема. Прототип или скетчи интерфейса (1 – 4-я недели).

Оформление введения и исследовательской части. Обоснование выбора БД, логическая схема БД, физическая схема данных. Демонстрация работы макета системы с БД (5 – 7-я недели).

Оформление проектно-конструкторской части. Демонстрация работающего приложения. Презентация (альфа). Тестирование и откладка приложения. Разработка эксплуатационной документации. (8 – 10-я недели).

Завершающее оформление документации согласно требованиям ГОСТ. Все ошибки и проблемы устранены. Подготовка доклада. Защита курсовой работы (11 – 14-я недели).

1.5. Порядок контроля и приемки системы

Система разрабатывается с применением тестирования работоспособности функционала. При добавлении новых функций предыдущие тесты должны сохранять работоспособность.
Приемка работы осуществляется комиссией КФ МГТУ им. Н. Э. Баумана кафедры ИУК5.

1.6. Требования к документированию
Требуется предоставить:

Техническое задание в соответствии с ГОСТ 34.602-89
Расчетно-пояснительную записку, включающую исследовательскую часть, проектно-конструкторскую часть и проектно-технологическую часть, включающую в себя руководство пользователя и руководство программиста (администратора). Расчетно-пояснительная записка выполняется с учетом требований, предусмотренных ГОСТ 7.32-2001 и 2.105-95.

**Comment by wldmr-key** [comment]
отлично
