### ISSUE TITLE
Создать концептуальную схему данных предметной области

### ISSUE THREAD

**Issue by KPbISSKA** [KPbISSKA/Tarasow_Aleksander#5]

**Comment by KPbISSKA** [comment]
![Концептуальная схема](https://user-images.githubusercontent.com/113367402/192531857-f4628f9b-d1d4-482d-9424-f04efa483213.JPG)

**Comment by KPbISSKA** [comment]
![image](https://user-images.githubusercontent.com/113367402/193643878-dd80a0bd-6742-4bed-8c67-5f44d25b1239.png)

**Comment by wldmr-key** [comment]
вот здесь отсутствие надписей на стрелках запутывает. И, кстати, создается впечатление, что связей недостаточно, исходя из описания предметной области... Да и атрибутов, похоже, недостаточно (удаление, например). А прохождение модуля где?

**Comment by KPbISSKA** [comment]
![image](https://user-images.githubusercontent.com/113367402/193896292-fa36181d-6e4b-4c34-b7f2-c293aa206327.png)

**Comment by KPbISSKA** [comment]
![image](https://user-images.githubusercontent.com/113367402/193900150-ba225dee-5022-49a6-a916-188f5067de19.png)
