### ISSUE TITLE
Создать логическую схему реляционной базы данных

### ISSUE THREAD

**Issue by KPbISSKA** [KPbISSKA/Tarasow_Aleksander#8]

**Comment by KPbISSKA** [comment]
![image](https://user-images.githubusercontent.com/113367402/196508752-3da90704-23d8-4ecb-9eb1-37dc3761f552.png)

**Comment by wldmr-key** [comment]
навскидку норм. Как быть с многозначными словами не очень понятно. В общем, посмотрим, как это пройдет испытание практикой ))
